<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'sebastianbergmann\\diff\\chunk' => '/Chunk.php',
                'sebastianbergmann\\diff\\diff' => '/Diff.php',
                'sebastianbergmann\\diff\\differ' => '/Differ.php',
                'sebastianbergmann\\diff\\line' => '/Line.php',
                'sebastianbergmann\\diff\\parser' => '/Parser.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd